import type { Attraction } from "./types";

const T = "/images/tourism";
const MAP = "/images/camiguin-tourist-map.png";

function loc(en: string, fil = en, bis = en) {
  return { en, fil, bis };
}

function ellipse(cx: number, cy: number, rx = 3.2, ry = 2.6) {
  // Approximate oval hit region in 0–100 viewBox
  return `M ${cx - rx} ${cy} a ${rx} ${ry} 0 1 0 ${rx * 2} 0 a ${rx} ${ry} 0 1 0 ${-rx * 2} 0`;
}

/** Tourism-only catalog aligned to camiguin-tourist-map.png */
export const CAMIGUIN_ATTRACTIONS: Attraction[] = [
  {
    id: "white-island",
    name: loc("White Island", "White Island", "White Island"),
    description: loc(
      "A sandbar of white coral sand off the northern coast—perfect for swimming and photo stops with Hibok-Hibok in the background.",
      "Isang sandbar ng puting coral sand sa hilagang baybayin—ideal para sa paglangoy at litrato na may tanaw ang Hibok-Hibok.",
      "Sandbar nga puti nga coral sand sa amihanang baybayon—maayo sa paglangoy ug litrato uban ang Hibok-Hibok."
    ),
    category: "beach",
    x: 18,
    y: 10,
    region: ellipse(18, 10, 4, 3),
    photos: [`${T}/tourism-white-island.png`, MAP],
    openingHours: loc("Day tours, weather dependent", "Day tours, depende sa panahon", "Day tours, depende sa panahon"),
    entranceFee: loc("Boat hire + eco fee (varies)", "Boat hire + eco fee (nag-iiba)", "Boat hire + eco fee (naglainlain)"),
    rating: 4.8,
    travelTips: loc("Go early for calmer seas and softer light.", "Pumunta nang maaga para sa mas tahimik na dagat.", "Sayoa aron kalmado ang dagat."),
    travelTime: loc("~25–40 min by boat from Yumbing", "~25–40 min sakay bangka mula Yumbing", "~25–40 min sakay bangka gikan Yumbing"),
    distanceFromCapitol: loc("~12 km + boat", "~12 km + bangka", "~12 km + bangka"),
  },
  {
    id: "mantigue-island",
    name: loc("Mantigue Island", "Mantigue Island", "Mantigue Island"),
    description: loc(
      "A small island sanctuary with white sand, snorkeling, and a short forest walk.",
      "Maliit na isla na may puting buhangin, snorkeling, at maikling lakad sa gubat.",
      "Gamay nga isla nga puti ang balas, snorkeling, ug mubo nga lakaw sa lasang."
    ),
    category: "marine",
    x: 86,
    y: 51,
    region: ellipse(86, 51, 3.5, 3),
    photos: [`${T}/tourism-mantigue-island.png`, MAP],
    openingHours: loc("Daytime, weather dependent", "Araw, depende sa panahon", "Adlaw, depende sa panahon"),
    entranceFee: loc("Island + boat fees apply", "May bayad sa isla at bangka", "May bayad sa isla ug bangka"),
    rating: 4.7,
    travelTips: loc("Bring reef-safe sunscreen and water shoes.", "Magdala ng reef-safe sunscreen at water shoes.", "Dad-a ang reef-safe sunscreen ug water shoes."),
    travelTime: loc("~20–30 min by boat from Benoni", "~20–30 min bangka mula Benoni", "~20–30 min bangka gikan Benoni"),
    distanceFromCapitol: loc("~18 km + boat", "~18 km + bangka", "~18 km + bangka"),
  },
  {
    id: "sunken-cemetery",
    name: loc("Sunken Cemetery", "Sunken Cemetery", "Sunken Cemetery"),
    description: loc(
      "A submerged cemetery marked by a large cross offshore—iconic after the 1871 eruption.",
      "Lumulutang na sementeryo na may malaking krus sa dagat—kilala pagkatapos ng pagsabog noong 1871.",
      "Lubog nga sementeryo nga may dakong krus sa dagat—nailhan human sa 1871 nga pagbuto."
    ),
    category: "landmark",
    x: 13,
    y: 28,
    region: ellipse(13, 28),
    photos: [`${T}/tourism-sunken-cemetery.png`, MAP],
    openingHours: loc("Daylight hours", "Oras ng araw", "Oras sa adlaw"),
    entranceFee: loc("Viewing free; boat optional", "Libre tumingin; optional ang bangka", "Libre tan-awon; optional ang bangka"),
    rating: 4.6,
    travelTips: loc("Best at golden hour from the shoreline viewpoint.", "Pinakamaganda sa golden hour mula sa baybayin.", "Pinakamaayo sa golden hour gikan sa baybayon."),
    travelTime: loc("~25 min drive from Mambajao", "~25 min biyahe mula Mambajao", "~25 min biyahe gikan Mambajao"),
    distanceFromCapitol: loc("~10 km", "~10 km", "~10 km"),
  },
  {
    id: "old-church-ruins",
    name: loc("Old Church Ruins", "Guho ng Lumang Simbahan", "Guba sa Daang Simbahan"),
    description: loc(
      "Guiob Church ruins—stone walls left from volcanic destruction, a quiet heritage stop.",
      "Guho ng Guiob Church—mga batong pader na natira mula sa pagsabog, tahimik na heritage stop.",
      "Guba sa Guiob Church—mga bato nga nahabilin human sa pagbuto, hilom nga heritage stop."
    ),
    category: "church",
    x: 16,
    y: 34,
    region: ellipse(16, 34),
    photos: [`${T}/tourism-guiob-church-ruins.png`, MAP],
    openingHours: loc("Daylight hours", "Oras ng araw", "Oras sa adlaw"),
    entranceFee: loc("Usually free / donation", "Karaniwang libre / donasyon", "Kasagaran libre / donasyon"),
    rating: 4.4,
    travelTips: loc("Combine with Sunken Cemetery on the same loop.", "Isama sa Sunken Cemetery sa iisang biyahe.", "Iuban sa Sunken Cemetery sa usa ka biyahe."),
    travelTime: loc("~25 min from Mambajao", "~25 min mula Mambajao", "~25 min gikan Mambajao"),
    distanceFromCapitol: loc("~11 km", "~11 km", "~11 km"),
  },
  {
    id: "katibawasan-falls",
    name: loc("Katibawasan Falls", "Katibawasan Falls", "Katibawasan Falls"),
    description: loc(
      "A towering waterfall cascading into a cool pool—one of Camiguin’s signature nature spots.",
      "Mataas na talon na bumabagsak sa malamig na pool—isa sa signature nature spots ng Camiguin.",
      "Taas nga busay nga nahulog sa bugnaw nga pool—usa sa signature nature spots sa Camiguin."
    ),
    category: "falls",
    x: 47,
    y: 34,
    region: ellipse(47, 34),
    photos: [`${T}/tourism-katibawasan-falls.png`, MAP],
    openingHours: loc("Typically 8:00 AM – 5:00 PM", "Karaniwang 8:00 AM – 5:00 PM", "Kasagaran 8:00 AM – 5:00 PM"),
    entranceFee: loc("Local eco / entrance fee", "Lokal na eco / entrance fee", "Lokal nga eco / entrance fee"),
    rating: 4.7,
    travelTips: loc("Wear shoes with grip; rocks can be slippery.", "Magsuot ng sapatos na may grip; madulas ang bato.", "Pagsul-ob og sapatos nga may grip; dangog ang bato."),
    travelTime: loc("~20–30 min from Mambajao", "~20–30 min mula Mambajao", "~20–30 min gikan Mambajao"),
    distanceFromCapitol: loc("~8 km", "~8 km", "~8 km"),
  },
  {
    id: "tuasan-falls",
    name: loc("Tuasan Falls", "Tuasan Falls", "Tuasan Falls"),
    description: loc(
      "A scenic inland waterfall popular for short treks and cooling off.",
      "Scenic na inland waterfall para sa maikling trek at pagpapalamig.",
      "Scenic nga inland waterfall para sa mubo nga trek ug pagpabugnaw."
    ),
    category: "falls",
    x: 38,
    y: 51,
    region: ellipse(38, 51),
    photos: [`${T}/tourism-tuasan-falls.png`, MAP],
    openingHours: loc("Daylight hours", "Oras ng araw", "Oras sa adlaw"),
    entranceFee: loc("Local fee may apply", "Maaaring may lokal na bayad", "Mahimong may lokal nga bayad"),
    rating: 4.5,
    travelTips: loc("Ask locals about trail conditions after heavy rain.", "Magtanong sa locals tungkol sa trail pagkatapos ng malakas na ulan.", "Pangutana sa locals bahin sa trail human sa kusog nga ulan."),
    travelTime: loc("~35–45 min from Mambajao", "~35–45 min mula Mambajao", "~35–45 min gikan Mambajao"),
    distanceFromCapitol: loc("~14 km", "~14 km", "~14 km"),
  },
  {
    id: "binangawan-falls",
    name: loc("Binangawan Falls", "Binangawan Falls", "Binangawan Falls"),
    description: loc(
      "A multi-tier waterfall experience with a rewarding trek atmosphere.",
      "Multi-tier na waterfall na may rewarding trek.",
      "Multi-tier nga waterfall nga rewarding ang trek."
    ),
    category: "falls",
    x: 55,
    y: 55,
    region: ellipse(55, 55),
    photos: [`${T}/tourism-binangawan-falls.png`, MAP],
    openingHours: loc("Daylight hours", "Oras ng araw", "Oras sa adlaw"),
    entranceFee: loc("Guide / entrance may apply", "Maaaring may guide / entrance", "Mahimong may guide / entrance"),
    rating: 4.5,
    travelTips: loc("Hire a local guide for safer footing on wet trails.", "Kumuha ng local guide para sa mas ligtas na daanan.", "Kuha og local guide para mas luwas ang dalan."),
    travelTime: loc("~40–60 min from Mambajao", "~40–60 min mula Mambajao", "~40–60 min gikan Mambajao"),
    distanceFromCapitol: loc("~16 km", "~16 km", "~16 km"),
  },
  {
    id: "soda-water-pool",
    name: loc("Soda Water Pool", "Soda Water Pool", "Soda Water Pool"),
    description: loc(
      "Bura Natural Soda Water Pool—naturally carbonated spring water in a landscaped pool setting.",
      "Bura Natural Soda Water Pool—natural na carbonated spring water sa landscaped pool.",
      "Bura Natural Soda Water Pool—natural nga carbonated spring water sa landscaped pool."
    ),
    category: "cold_spring",
    x: 22,
    y: 48,
    region: ellipse(22, 48),
    photos: [`${T}/tourism-bura-soda-pool.png`, MAP],
    openingHours: loc("Typically daytime", "Karaniwang araw", "Kasagaran adlaw"),
    entranceFee: loc("Entrance fee applies", "May entrance fee", "May entrance fee"),
    rating: 4.3,
    travelTips: loc("Great stop for families between northern sites.", "Magandang stop para sa pamilya sa pagitan ng northern sites.", "Maayo nga stop para sa pamilya taliwala sa northern sites."),
    travelTime: loc("~15–25 min from Mambajao", "~15–25 min mula Mambajao", "~15–25 min gikan Mambajao"),
    distanceFromCapitol: loc("~6 km", "~6 km", "~6 km"),
  },
  {
    id: "ardent-hot-spring",
    name: loc("Ardent Hot Spring", "Ardent Hot Spring", "Ardent Hot Spring"),
    description: loc(
      "Volcanic hot spring pools set in a lush hillside resort atmosphere.",
      "Volcanic hot spring pools sa lush na hillside resort.",
      "Volcanic hot spring pools sa lush nga hillside resort."
    ),
    category: "hot_spring",
    x: 40,
    y: 24,
    region: ellipse(40, 24),
    photos: [`${T}/tourism-ardent-hot-springs.png`, MAP],
    openingHours: loc("Often open into evening", "Madalas bukas hanggang gabi", "Kanunay abli hangtod gabii"),
    entranceFee: loc("Resort / pool fees apply", "May resort / pool fees", "May resort / pool fees"),
    rating: 4.6,
    travelTips: loc("Bring a change of clothes and arrive before peak evening crowds.", "Magdala ng palit at dumating bago madaming tao sa gabi.", "Dad-a ang ilisan ug sayo sa gabii aron dili daghan ang tawo."),
    travelTime: loc("~15–20 min from Mambajao", "~15–20 min mula Mambajao", "~15–20 min gikan Mambajao"),
    distanceFromCapitol: loc("~5 km", "~5 km", "~5 km"),
  },
  {
    id: "sto-nino-cold-spring",
    name: loc("Sto Niño Cold Spring", "Sto Niño Cold Spring", "Sto Niño Cold Spring"),
    description: loc(
      "Crystal-clear cold spring pools ideal for swimming and weekend family visits.",
      "Malinaw na cold spring pools para sa paglangoy at family weekend.",
      "Klaro nga cold spring pools para sa paglangoy ug family weekend."
    ),
    category: "cold_spring",
    x: 42,
    y: 64,
    region: ellipse(42, 64),
    photos: [`${T}/tourism-sto-nino-cold-spring.png`, MAP],
    openingHours: loc("Daytime", "Araw", "Adlaw"),
    entranceFee: loc("Entrance fee applies", "May entrance fee", "May entrance fee"),
    rating: 4.5,
    travelTips: loc("Weekends get busy—visit earlier in the day.", "Masikip tuwing weekend—pumunta nang mas maaga.", "Daghan sa weekend—sayoa."),
    travelTime: loc("~35–50 min from Mambajao", "~35–50 min mula Mambajao", "~35–50 min gikan Mambajao"),
    distanceFromCapitol: loc("~15 km", "~15 km", "~15 km"),
  },
  {
    id: "volcano-observatory",
    name: loc("Volcano Observatory", "Volcano Observatory", "Volcano Observatory"),
    description: loc(
      "PHIVOLCS monitoring viewpoint for Hibok-Hibok with educational context on volcanic activity.",
      "Viewpoint ng PHIVOLCS para sa Hibok-Hibok na may educational context tungkol sa aktibidad ng bulkan.",
      "Viewpoint sa PHIVOLCS para sa Hibok-Hibok nga may educational context bahin sa aktibidad sa bulkan."
    ),
    category: "landmark",
    x: 32,
    y: 30,
    region: ellipse(32, 30),
    photos: [MAP, `${T}/tourism-mt-hibok-hibok.png`],
    openingHours: loc("Check on-site schedule", "Tingnan ang schedule on-site", "Tan-awa ang schedule on-site"),
    entranceFee: loc("May vary / donation", "Maaaring mag-iba / donasyon", "Mahimong maglain / donasyon"),
    rating: 4.2,
    travelTips: loc("Pair with Ardent Hot Spring nearby.", "Isama sa Ardent Hot Spring na malapit.", "Iuban sa duol nga Ardent Hot Spring."),
    travelTime: loc("~20 min from Mambajao", "~20 min mula Mambajao", "~20 min gikan Mambajao"),
    distanceFromCapitol: loc("~7 km", "~7 km", "~7 km"),
  },
  {
    id: "mt-hibok-hibok",
    name: loc("Mt. Hibok-Hibok", "Mt. Hibok-Hibok", "Mt. Hibok-Hibok"),
    description: loc(
      "Camiguin’s active volcano and hiking icon—permits and guides are recommended.",
      "Aktibong bulkan at hiking icon ng Camiguin—inirerekomenda ang permit at guide.",
      "Aktibong bulkan ug hiking icon sa Camiguin—girekomendar ang permit ug guide."
    ),
    category: "volcano",
    x: 34,
    y: 37,
    region: ellipse(34, 37, 4, 3.5),
    photos: [`${T}/tourism-mt-hibok-hibok.png`, MAP],
    openingHours: loc("Trek by arrangement / daylight", "Trek ayon sa arrangement / araw", "Trek sumala sa arrangement / adlaw"),
    entranceFee: loc("Guide + climb fees", "Guide + climb fees", "Guide + climb fees"),
    rating: 4.8,
    travelTips: loc("Only hike with accredited guides and check weather alerts.", "Mag-hike lamang kasama ang accredited guides at tingnan ang weather alerts.", "Pag-hike uban ang accredited guides ug check weather alerts."),
    travelTime: loc("Half-day to full-day trek", "Half-day hanggang full-day trek", "Half-day hangtod full-day trek"),
    distanceFromCapitol: loc("~8 km to trailheads", "~8 km papunta sa trailheads", "~8 km padulong sa trailheads"),
  },
  {
    id: "giant-clam-sanctuary",
    name: loc("Giant Clam Sanctuary", "Giant Clam Sanctuary", "Giant Clam Sanctuary"),
    description: loc(
      "A marine conservation site showcasing giant clams in clear coastal waters.",
      "Marine conservation site na may giant clams sa malinaw na baybayin.",
      "Marine conservation site nga may giant clams sa klaro nga baybayon."
    ),
    category: "marine",
    x: 78,
    y: 72,
    region: ellipse(78, 72),
    photos: [`${T}/tourism-giant-clam-sanctuary.png`, MAP],
    openingHours: loc("Daytime, tide dependent", "Araw, depende sa tide", "Adlaw, depende sa tide"),
    entranceFee: loc("Eco / viewing fee", "Eco / viewing fee", "Eco / viewing fee"),
    rating: 4.4,
    travelTips: loc("Do not touch or step on coral and clams.", "Huwag hawakan o tapakan ang coral at clams.", "Ayaw hikapa o latagan ang coral ug clams."),
    travelTime: loc("~40–55 min from Mambajao", "~40–55 min mula Mambajao", "~40–55 min gikan Mambajao"),
    distanceFromCapitol: loc("~20 km", "~20 km", "~20 km"),
  },
  {
    id: "cabuan-eco-village",
    name: loc("Cabuan Eco Village", "Cabuan Eco Village", "Cabuan Eco Village"),
    description: loc(
      "Community eco-tourism village experience highlighting local culture and nature.",
      "Community eco-tourism village na nagha-highlight ng lokal na kultura at kalikasan.",
      "Community eco-tourism village nga nag-highlight sa lokal nga kultura ug kinaiyahan."
    ),
    category: "village",
    x: 72,
    y: 72,
    region: ellipse(72, 72),
    photos: [MAP, `${T}/tourism-taguines-lagoon.png`],
    openingHours: loc("By arrangement / daytime", "By arrangement / araw", "By arrangement / adlaw"),
    entranceFee: loc("Community fees may apply", "Maaaring may community fees", "Mahimong may community fees"),
    rating: 4.3,
    travelTips: loc("Support local guides and buy village products.", "Suportahan ang local guides at bumili ng produkto ng barangay.", "Suportahi ang local guides ug palit og produkto sa barangay."),
    travelTime: loc("~50–70 min from Mambajao", "~50–70 min mula Mambajao", "~50–70 min gikan Mambajao"),
    distanceFromCapitol: loc("~25 km", "~25 km", "~25 km"),
  },
  {
    id: "moro-watch-tower",
    name: loc("Moro Watch Tower", "Moro Watch Tower", "Moro Watch Tower"),
    description: loc(
      "Historic coastal watchtower ruins reflecting Camiguin’s maritime heritage.",
      "Historikong guho ng coastal watchtower na sumasalamin sa maritime heritage ng Camiguin.",
      "Historikong guba sa coastal watchtower nga nagpakita sa maritime heritage sa Camiguin."
    ),
    category: "landmark",
    x: 68,
    y: 84,
    region: ellipse(68, 84),
    photos: [MAP],
    openingHours: loc("Daylight hours", "Oras ng araw", "Oras sa adlaw"),
    entranceFee: loc("Usually free", "Karaniwang libre", "Kasagaran libre"),
    rating: 4.1,
    travelTips: loc("Good quick stop while looping the southern road.", "Magandang mabilis na stop sa southern road loop.", "Maayo nga dali nga stop sa southern road loop."),
    travelTime: loc("~55–75 min from Mambajao", "~55–75 min mula Mambajao", "~55–75 min gikan Mambajao"),
    distanceFromCapitol: loc("~28 km", "~28 km", "~28 km"),
  },
  {
    id: "walkway-old-volcano",
    name: loc("Walkway to the Old Volcano", "Walkway papunta sa Old Volcano", "Walkway padulong sa Old Volcano"),
    description: loc(
      "A long stairway pilgrimage route toward Old Volcano stations with island panoramas.",
      "Mahabang stairway pilgrimage route papunta sa Old Volcano stations na may panorama ng isla.",
      "Taas nga stairway pilgrimage route padulong sa Old Volcano stations nga may panorama sa isla."
    ),
    category: "landmark",
    x: 22,
    y: 38,
    region: ellipse(22, 38, 3.5, 4),
    photos: [`${T}/tourism-walkway-old-volcano.png`, MAP],
    openingHours: loc("Daylight; busiest in Holy Week", "Araw; pinakasikip sa Holy Week", "Adlaw; pinakasiksik sa Holy Week"),
    entranceFee: loc("Usually free / local fee", "Karaniwang libre / lokal na bayad", "Kasagaran libre / lokal nga bayad"),
    rating: 4.6,
    travelTips: loc("Bring water; the climb is longer than it looks.", "Magdala ng tubig; mas mahaba ang akyat kaysa inaakala.", "Dad-a ang tubig; mas taas ang saka kay sa imong hunahuna."),
    travelTime: loc("~30–40 min from Mambajao to base", "~30–40 min mula Mambajao hanggang base", "~30–40 min gikan Mambajao hangtod base"),
    distanceFromCapitol: loc("~12 km", "~12 km", "~12 km"),
  },
  {
    id: "macau-springs",
    name: loc("Macau Springs", "Macau Springs", "Macau Springs"),
    description: loc(
      "Natural spring pools known locally for cool freshwater swimming.",
      "Natural spring pools na kilala sa malamig na freshwater swimming.",
      "Natural spring pools nga nailhan sa bugnaw nga freshwater swimming."
    ),
    category: "cold_spring",
    x: 70,
    y: 36,
    region: ellipse(70, 36),
    photos: [MAP, `${T}/tourism-sto-nino-cold-spring.png`],
    openingHours: loc("Daytime", "Araw", "Adlaw"),
    entranceFee: loc("Local fee may apply", "Maaaring may lokal na bayad", "Mahimong may lokal nga bayad"),
    rating: 4.2,
    travelTips: loc("Confirm access with locals—some springs are privately managed.", "Kumpirmahin ang access sa locals—may pribadong springs.", "Kumpirmaha ang access sa locals—may pribadong springs."),
    travelTime: loc("~40–55 min from Mambajao", "~40–55 min mula Mambajao", "~40–55 min gikan Mambajao"),
    distanceFromCapitol: loc("~17 km", "~17 km", "~17 km"),
  },
  {
    id: "benoni-port",
    name: loc("Benoni Port", "Pantalan ng Benoni", "Pantalan sa Benoni"),
    description: loc(
      "Main ferry gateway connecting Camiguin with Mindanao mainland routes.",
      "Pangunahing ferry gateway na nag-uugnay sa Camiguin at Mindanao mainland.",
      "Panguna nga ferry gateway nga nagkonektar sa Camiguin ug Mindanao mainland."
    ),
    category: "port",
    x: 74,
    y: 48,
    region: ellipse(74, 48),
    photos: [MAP, `${T}/tourism-taguines-lagoon.png`],
    openingHours: loc("Ferry schedule based", "Ayon sa ferry schedule", "Sumala sa ferry schedule"),
    entranceFee: loc("Terminal / ferry tickets", "Terminal / ferry tickets", "Terminal / ferry tickets"),
    rating: 4.0,
    travelTips: loc("Arrive early for peak holiday sailings.", "Dumating nang maaga sa peak holiday sailings.", "Sayoa sa peak holiday sailings."),
    travelTime: loc("~35–45 min from Mambajao", "~35–45 min mula Mambajao", "~35–45 min gikan Mambajao"),
    distanceFromCapitol: loc("~16 km", "~16 km", "~16 km"),
  },
  {
    id: "balbagon-port",
    name: loc("Balbagon Port", "Pantalan ng Balbagon", "Pantalan sa Balbagon"),
    description: loc(
      "Mambajao-area port used for local boat and passenger connections.",
      "Pantalan sa may Mambajao para sa lokal na bangka at pasahero.",
      "Pantalan duol sa Mambajao para sa lokal nga bangka ug pasahero."
    ),
    category: "port",
    x: 56,
    y: 12,
    region: ellipse(56, 12),
    photos: [MAP],
    openingHours: loc("Daytime / schedule based", "Araw / ayon sa schedule", "Adlaw / sumala sa schedule"),
    entranceFee: loc("Boat fares vary", "Nag-iiba ang pamasahe sa bangka", "Naglainlain ang pliti sa bangka"),
    rating: 3.9,
    travelTips: loc("Useful when arranging northern island boat trips.", "Kapaki-pakinabang para sa northern island boat trips.", "Makatabang para sa northern island boat trips."),
    travelTime: loc("~10–15 min from Capitol", "~10–15 min mula Capitol", "~10–15 min gikan Capitol"),
    distanceFromCapitol: loc("~4 km", "~4 km", "~4 km"),
  },
  {
    id: "airport",
    name: loc("Camiguin Airport", "Paliparan ng Camiguin", "Tugpahanan sa Camiguin"),
    description: loc(
      "Island airport serving limited commercial flights to and from Camiguin.",
      "Paliparan ng isla na may limited commercial flights papunta at mula Camiguin.",
      "Tugpahanan sa isla nga may limited commercial flights padulong ug gikan Camiguin."
    ),
    category: "landmark",
    x: 64,
    y: 22,
    region: ellipse(64, 22, 3.8, 2.8),
    photos: [MAP],
    openingHours: loc("Flight schedule based", "Ayon sa flight schedule", "Sumala sa flight schedule"),
    entranceFee: loc("Airline tickets", "Airline tickets", "Airline tickets"),
    rating: 4.0,
    travelTips: loc("Confirm flights ahead—schedules can change with weather.", "Kumpirmahin ang flights—maaaring magbago ang schedule dahil sa panahon.", "Kumpirmaha ang flights—mahimong maglain ang schedule tungod sa panahon."),
    travelTime: loc("~15–25 min from Mambajao", "~15–25 min mula Mambajao", "~15–25 min gikan Mambajao"),
    distanceFromCapitol: loc("~7 km", "~7 km", "~7 km"),
  },
];

export function getAttractionById(id: string) {
  return CAMIGUIN_ATTRACTIONS.find((a) => a.id === id) ?? null;
}
