export type EventScheduleItem = {
  dayEn: string;
  dayFil: string;
  dayBis: string;
  timeEn?: string;
  timeFil?: string;
  timeBis?: string;
  titleEn: string;
  titleFil: string;
  titleBis: string;
  descriptionEn?: string;
  descriptionFil?: string;
  descriptionBis?: string;
  location?: string;
};

export type EventDetailPack = {
  overviewEn?: string;
  overviewFil?: string;
  overviewBis?: string;
  highlightsEn?: string[];
  highlightsFil?: string[];
  highlightsBis?: string[];
  schedule?: EventScheduleItem[];
};

/** Extra detail packs keyed by Event.titleEn. Shown when an event card is opened. */
export const EVENT_DETAILS_BY_TITLE: Record<string, EventDetailPack> = {
  "Lanzones Festival": {
    overviewEn:
      "Camiguin’s signature harvest thanksgiving in Mambajao. Expect street dancing, the Ugmad agri-tourism fair, pageants, concerts, and lanzones feasts across the week.",
    overviewFil:
      "Pangunahing harvest thanksgiving ng Camiguin sa Mambajao. May street dancing, Ugmad agri-tourism fair, pageant, konsiyerto, at lanzones feasts sa buong linggo.",
    overviewBis:
      "Pangunang harvest thanksgiving sa Camiguin sa Mambajao. Adunay street dancing, Ugmad agri-tourism fair, pageant, konsiyerto, ug lanzones feasts sa tibuok semana.",
    highlightsEn: [
      "Ugmad Agro-Industrial-Tourism Trade Fair",
      "Inter-Agency Street Dancing Competition",
      "Mutya sa Buahanan Coronation Night",
      "Lanzones Eat-All-You-Can",
      "Festival concerts and food bazaars",
    ],
    highlightsFil: [
      "Ugmad Agro-Industrial-Tourism Trade Fair",
      "Inter-Agency Street Dancing Competition",
      "Mutya sa Buahanan Coronation Night",
      "Lanzones Eat-All-You-Can",
      "Mga festival concert at food bazaar",
    ],
    highlightsBis: [
      "Ugmad Agro-Industrial-Tourism Trade Fair",
      "Inter-Agency Street Dancing Competition",
      "Mutya sa Buahanan Coronation Night",
      "Lanzones Eat-All-You-Can",
      "Mga festival concert ug food bazaar",
    ],
    schedule: [
      {
        dayEn: "Oct 20",
        dayFil: "Okt 20",
        dayBis: "Okt 20",
        timeEn: "8:00 AM",
        timeFil: "8:00 AM",
        timeBis: "8:00 AM",
        titleEn: "Opening Ceremonies",
        titleFil: "Opening Ceremonies",
        titleBis: "Opening Ceremonies",
        descriptionEn: "Official festival opening with provincial officials and cultural welcome.",
        descriptionFil: "Opisyal na pagbubukas ng festival kasama ang mga opisyal ng lalawigan at cultural welcome.",
        descriptionBis: "Opisyal nga pag-abli sa festival uban ang mga opisyal sa lalawigan ug cultural welcome.",
        location: "Mambajao Town Plaza",
      },
      {
        dayEn: "Oct 20",
        dayFil: "Okt 20",
        dayBis: "Okt 20",
        timeEn: "10:00 AM",
        timeFil: "10:00 AM",
        timeBis: "10:00 AM",
        titleEn: "Ugmad Agro-Industrial-Tourism Fair Opening",
        titleFil: "Pagbubukas ng Ugmad Agro-Industrial-Tourism Fair",
        titleBis: "Pag-abli sa Ugmad Agro-Industrial-Tourism Fair",
        descriptionEn: "Opening of the weeklong agri-tourism trade fair featuring Camiguin products.",
        descriptionFil: "Pagbubukas ng weeklong agri-tourism trade fair na may produkto ng Camiguin.",
        descriptionBis: "Pag-abli sa weeklong agri-tourism trade fair nga adunay produkto sa Camiguin.",
        location: "Capitol Grounds, Mambajao",
      },
      {
        dayEn: "Oct 20",
        dayFil: "Okt 20",
        dayBis: "Okt 20",
        timeEn: "6:00 PM",
        timeFil: "6:00 PM",
        timeBis: "6:00 PM",
        titleEn: "Welcome Cultural Night & Food Bazaar",
        titleFil: "Welcome Cultural Night at Food Bazaar",
        titleBis: "Welcome Cultural Night ug Food Bazaar",
        descriptionEn: "Opening-night cultural presentations and DAOS KI festival food stalls.",
        descriptionFil: "Cultural presentations sa opening night at DAOS KI festival food stalls.",
        descriptionBis: "Cultural presentations sa opening night ug DAOS KI festival food stalls.",
        location: "Ugmad Fair Grounds",
      },
      {
        dayEn: "Oct 21",
        dayFil: "Okt 21",
        dayBis: "Okt 21",
        timeEn: "8:00 AM",
        timeFil: "8:00 AM",
        timeBis: "8:00 AM",
        titleEn: "Ugmad Fair Day · Local Product Exhibits",
        titleFil: "Ugmad Fair Day · Local Product Exhibits",
        titleBis: "Ugmad Fair Day · Local Product Exhibits",
        descriptionEn: "Farm produce, lanzones products, handicrafts, and MSME booths open all day.",
        descriptionFil: "Farm produce, produkto ng lanzones, handicrafts, at MSME booths buong araw.",
        descriptionBis: "Farm produce, produkto sa lanzones, handicrafts, ug MSME booths tibuok adlaw.",
        location: "Ugmad Fair Grounds, Mambajao",
      },
      {
        dayEn: "Oct 21",
        dayFil: "Okt 21",
        dayBis: "Okt 21",
        timeEn: "2:00 PM",
        timeFil: "2:00 PM",
        timeBis: "2:00 PM",
        titleEn: "Kadiwa sa Ugmad Market Activities",
        titleFil: "Mga Aktibidad ng Kadiwa sa Ugmad",
        titleBis: "Mga Kalihokan sa Kadiwa sa Ugmad",
        descriptionEn: "Market activities supporting local farmers and small food enterprises.",
        descriptionFil: "Mga market activity na sumusuporta sa magsasaka at maliliit na food enterprise.",
        descriptionBis: "Mga market activity nga nagsuporta sa mga mag-uuma ug gagmay nga food enterprise.",
        location: "Capitol Grounds",
      },
      {
        dayEn: "Oct 21",
        dayFil: "Okt 21",
        dayBis: "Okt 21",
        timeEn: "7:00 PM",
        timeFil: "7:00 PM",
        timeBis: "7:00 PM",
        titleEn: "DAOS KI Festival Food Bazaar Night",
        titleFil: "DAOS KI Festival Food Bazaar Night",
        titleBis: "DAOS KI Festival Food Bazaar Night",
        descriptionEn: "Evening food bazaar featuring Camiguin delicacies and festival street food.",
        descriptionFil: "Gabi ng food bazaar na may mga delicacies at festival street food ng Camiguin.",
        descriptionBis: "Gabii sa food bazaar nga adunay mga delicacies ug festival street food sa Camiguin.",
        location: "Ugmad Fair Grounds",
      },
      {
        dayEn: "Oct 22",
        dayFil: "Okt 22",
        dayBis: "Okt 22",
        timeEn: "9:00 AM",
        timeFil: "9:00 AM",
        timeBis: "9:00 AM",
        titleEn: "Agriculture & Fishery Forum Day",
        titleFil: "Araw ng Agriculture & Fishery Forum",
        titleBis: "Adlaw sa Agriculture & Fishery Forum",
        descriptionEn: "Sector forums and agri exhibits highlighting Camiguin’s farm and fishery programs.",
        descriptionFil: "Mga sector forum at agri exhibit tungkol sa farm at fishery programs ng Camiguin.",
        descriptionBis: "Mga sector forum ug agri exhibit bahin sa farm ug fishery programs sa Camiguin.",
        location: "Capitol Grounds / Activity Hall",
      },
      {
        dayEn: "Oct 22",
        dayFil: "Okt 22",
        dayBis: "Okt 22",
        timeEn: "1:00 PM",
        timeFil: "1:00 PM",
        timeBis: "1:00 PM",
        titleEn: "Community Cultural Showcases",
        titleFil: "Community Cultural Showcases",
        titleBis: "Community Cultural Showcases",
        descriptionEn: "Barangay and municipal cultural presentations throughout the afternoon.",
        descriptionFil: "Mga cultural presentation ng barangay at bayan sa buong hapon.",
        descriptionBis: "Mga cultural presentation sa barangay ug lungsod sa tibuok hapon.",
        location: "Mambajao Activity Area",
      },
      {
        dayEn: "Oct 22",
        dayFil: "Okt 22",
        dayBis: "Okt 22",
        timeEn: "7:00 PM",
        timeFil: "7:00 PM",
        timeBis: "7:00 PM",
        titleEn: "Battle of the Bands / Rocktober Night",
        titleFil: "Battle of the Bands / Rocktober Night",
        titleBis: "Battle of the Bands / Rocktober Night",
        descriptionEn: "Evening music competition and festival concert night.",
        descriptionFil: "Gabi ng music competition at festival concert.",
        descriptionBis: "Gabii sa music competition ug festival concert.",
        location: "Festival Mainstage, Mambajao",
      },
      {
        dayEn: "Oct 23",
        dayFil: "Okt 23",
        dayBis: "Okt 23",
        timeEn: "9:00 AM",
        timeFil: "9:00 AM",
        timeBis: "9:00 AM",
        titleEn: "Ugmad Fair Midweek · Lanzones Product Day",
        titleFil: "Ugmad Fair Midweek · Araw ng Produkto ng Lanzones",
        titleBis: "Ugmad Fair Midweek · Adlaw sa Produkto sa Lanzones",
        descriptionEn: "Special focus on lanzones products, tasting booths, and agri displays.",
        descriptionFil: "Espesyal na focus sa produkto ng lanzones, tasting booths, at agri displays.",
        descriptionBis: "Espesyal nga focus sa produkto sa lanzones, tasting booths, ug agri displays.",
        location: "Ugmad Fair Grounds",
      },
      {
        dayEn: "Oct 23",
        dayFil: "Okt 23",
        dayBis: "Okt 23",
        timeEn: "3:00 PM",
        timeFil: "3:00 PM",
        timeBis: "3:00 PM",
        titleEn: "Pasigarbo sa Camiguin Singing Star",
        titleFil: "Pasigarbo sa Camiguin Singing Star",
        titleBis: "Pasigarbo sa Camiguin Singing Star",
        descriptionEn: "Singing competition showcasing Camiguin’s local talent.",
        descriptionFil: "Singing competition na nagpapakita ng lokal na talento ng Camiguin.",
        descriptionBis: "Singing competition nga nagpakita sa lokal nga talento sa Camiguin.",
        location: "Festival Mainstage",
      },
      {
        dayEn: "Oct 23",
        dayFil: "Okt 23",
        dayBis: "Okt 23",
        timeEn: "7:00 PM",
        timeFil: "7:00 PM",
        timeBis: "7:00 PM",
        titleEn: "Festival Food Night & Cultural Presentations",
        titleFil: "Festival Food Night at Cultural Presentations",
        titleBis: "Festival Food Night ug Cultural Presentations",
        descriptionEn: "Night market food stalls with continuing cultural performances.",
        descriptionFil: "Night market food stalls at tuloy-tuloy na cultural performances.",
        descriptionBis: "Night market food stalls ug padayon nga cultural performances.",
        location: "Ugmad Fair Grounds",
      },
      {
        dayEn: "Oct 24",
        dayFil: "Okt 24",
        dayBis: "Okt 24",
        timeEn: "9:00 AM",
        timeFil: "9:00 AM",
        timeBis: "9:00 AM",
        titleEn: "Ugmad Fair Day · Tourism & Trade Booths",
        titleFil: "Ugmad Fair Day · Tourism at Trade Booths",
        titleBis: "Ugmad Fair Day · Tourism ug Trade Booths",
        descriptionEn: "Tourism desks, resort partners, and trade exhibits remain open for visitors.",
        descriptionFil: "Tourism desks, resort partners, at trade exhibits bukas para sa mga bisita.",
        descriptionBis: "Tourism desks, resort partners, ug trade exhibits abli para sa mga bisita.",
        location: "Capitol Grounds",
      },
      {
        dayEn: "Oct 24",
        dayFil: "Okt 24",
        dayBis: "Okt 24",
        timeEn: "2:00 PM",
        timeFil: "2:00 PM",
        timeBis: "2:00 PM",
        titleEn: "Buahanan DocuFest / Public Service Showcase",
        titleFil: "Buahanan DocuFest / Public Service Showcase",
        titleBis: "Buahanan DocuFest / Public Service Showcase",
        descriptionEn: "Multimedia and public service engagement activities for festival-goers.",
        descriptionFil: "Multimedia at public service engagement activities para sa mga dumalo.",
        descriptionBis: "Multimedia ug public service engagement activities para sa mga mitambong.",
        location: "Mambajao Activity Area",
      },
      {
        dayEn: "Oct 24",
        dayFil: "Okt 24",
        dayBis: "Okt 24",
        timeEn: "7:00 PM",
        timeFil: "7:00 PM",
        timeBis: "7:00 PM",
        titleEn: "Mutya sa Buahanan Coronation Night",
        titleFil: "Mutya sa Buahanan Coronation Night",
        titleBis: "Mutya sa Buahanan Coronation Night",
        descriptionEn: "Festival pageant crowning Camiguin’s Mutya sa Buahanan.",
        descriptionFil: "Festival pageant na kinoronahan ang Mutya sa Buahanan ng Camiguin.",
        descriptionBis: "Festival pageant nga magkorona sa Mutya sa Buahanan sa Camiguin.",
        location: "Mambajao Activity Area / Mainstage",
      },
      {
        dayEn: "Oct 25",
        dayFil: "Okt 25",
        dayBis: "Okt 25",
        timeEn: "8:00 AM",
        timeFil: "8:00 AM",
        timeBis: "8:00 AM",
        titleEn: "Inter-Agency Street Dancing Competition",
        titleFil: "Inter-Agency Street Dancing Competition",
        titleBis: "Inter-Agency Street Dancing Competition",
        descriptionEn: "Colorful street dancing parade along Mambajao’s festival route.",
        descriptionFil: "Makulay na street dancing parade sa festival route ng Mambajao.",
        descriptionBis: "Mabulukon nga street dancing parade sa festival route sa Mambajao.",
        location: "Provincial Plaza to Mambajao Activity Area",
      },
      {
        dayEn: "Oct 25",
        dayFil: "Okt 25",
        dayBis: "Okt 25",
        timeEn: "1:00 PM",
        timeFil: "1:00 PM",
        timeBis: "1:00 PM",
        titleEn: "Ground Presentation Competition",
        titleFil: "Ground Presentation Competition",
        titleBis: "Ground Presentation Competition",
        descriptionEn: "Contingents present full ground performances after the street parade.",
        descriptionFil: "Mga contingent na nagpe-present ng full ground performances pagkatapos ng street parade.",
        descriptionBis: "Mga contingent nga magpresent og full ground performances human sa street parade.",
        location: "Mambajao Activity Area",
      },
      {
        dayEn: "Oct 25",
        dayFil: "Okt 25",
        dayBis: "Okt 25",
        timeEn: "7:00 PM",
        timeFil: "7:00 PM",
        timeBis: "7:00 PM",
        titleEn: "Island Lights Festival Concert",
        titleFil: "Island Lights Festival Concert",
        titleBis: "Island Lights Festival Concert",
        descriptionEn: "Mainstage concert night closing the street-dancing day.",
        descriptionFil: "Mainstage concert night na nagsasara sa araw ng street dancing.",
        descriptionBis: "Mainstage concert night nga nagsira sa adlaw sa street dancing.",
        location: "Lanzones Festival Mainstage, Mambajao",
      },
      {
        dayEn: "Oct 26",
        dayFil: "Okt 26",
        dayBis: "Okt 26",
        timeEn: "8:00 AM",
        timeFil: "8:00 AM",
        timeBis: "8:00 AM",
        titleEn: "Lanzones Eat-All-You-Can",
        titleFil: "Lanzones Eat-All-You-Can",
        titleBis: "Lanzones Eat-All-You-Can",
        descriptionEn: "Harvest feast day featuring Camiguin’s signature sweet lanzones.",
        descriptionFil: "Araw ng harvest feast na may signature sweet lanzones ng Camiguin.",
        descriptionBis: "Adlaw sa harvest feast nga adunay signature sweet lanzones sa Camiguin.",
        location: "Capitol Grounds / Festival Booths",
      },
      {
        dayEn: "Oct 26",
        dayFil: "Okt 26",
        dayBis: "Okt 26",
        timeEn: "10:00 AM",
        timeFil: "10:00 AM",
        timeBis: "10:00 AM",
        titleEn: "Final Ugmad Fair Day & Grand Parade Highlights",
        titleFil: "Huling Araw ng Ugmad Fair at Grand Parade Highlights",
        titleBis: "Katapusang Adlaw sa Ugmad Fair ug Grand Parade Highlights",
        descriptionEn: "Last fair day with parade highlights and visitor activities around Mambajao.",
        descriptionFil: "Huling araw ng fair na may parade highlights at visitor activities sa Mambajao.",
        descriptionBis: "Katapusang adlaw sa fair uban ang parade highlights ug visitor activities sa Mambajao.",
        location: "Mambajao Town Plaza & Capitol Grounds",
      },
      {
        dayEn: "Oct 26",
        dayFil: "Okt 26",
        dayBis: "Okt 26",
        timeEn: "5:00 PM",
        timeFil: "5:00 PM",
        timeBis: "5:00 PM",
        titleEn: "Closing Thanksgiving Program",
        titleFil: "Closing Thanksgiving Program",
        titleBis: "Closing Thanksgiving Program",
        descriptionEn: "Festival closing rites and thanksgiving for Camiguin’s lanzones harvest.",
        descriptionFil: "Pagsasara ng festival at pasasalamat para sa ani ng lanzones ng Camiguin.",
        descriptionBis: "Pagsira sa festival ug pagpasalamat para sa ani sa lanzones sa Camiguin.",
        location: "Mambajao Town Plaza",
      },
    ],
  },

  "Sinulog de Camiguin": {
    overviewEn:
      "Mambajao’s devotion to the Santo Niño with processions, street dancing, trade fairs, and Camiguin cultural presentations.",
    overviewFil:
      "Debosyon ng Mambajao sa Santo Niño na may prusisyon, street dancing, trade fair, at cultural presentations ng Camiguin.",
    overviewBis:
      "Debosyon sa Mambajao sa Santo Niño uban ang prusisyon, street dancing, trade fair, ug cultural presentations sa Camiguin.",
    highlightsEn: [
      "Santo Niño procession",
      "Street dancing competition",
      "Local trade and food fair",
      "Cultural dance presentations",
    ],
    highlightsFil: [
      "Prusisyon ng Santo Niño",
      "Street dancing competition",
      "Local trade at food fair",
      "Mga cultural dance presentation",
    ],
    highlightsBis: [
      "Prusisyon sa Santo Niño",
      "Street dancing competition",
      "Local trade ug food fair",
      "Mga cultural dance presentation",
    ],
    schedule: [
      {
        dayEn: "Jan 18",
        dayFil: "Ene 18",
        dayBis: "Ene 18",
        timeEn: "8:00 AM",
        timeFil: "8:00 AM",
        timeBis: "8:00 AM",
        titleEn: "Holy Mass & Santo Niño Procession",
        titleFil: "Banal na Misa at Prusisyon ng Santo Niño",
        titleBis: "Balaang Misa ug Prusisyon sa Santo Niño",
        descriptionEn: "Morning mass and procession honoring the Santo Niño in Mambajao.",
        descriptionFil: "Umagang misa at prusisyon bilang pagpaparangal sa Santo Niño sa Mambajao.",
        descriptionBis: "Buntag nga misa ug prusisyon isip pagpasidungog sa Santo Niño sa Mambajao.",
        location: "Mambajao Parish / Town Plaza",
      },
      {
        dayEn: "Jan 18",
        dayFil: "Ene 18",
        dayBis: "Ene 18",
        timeEn: "1:00 PM",
        timeFil: "1:00 PM",
        timeBis: "1:00 PM",
        titleEn: "Street Dancing Competition",
        titleFil: "Street Dancing Competition",
        titleBis: "Street Dancing Competition",
        descriptionEn: "Colorful Sinulog street dancing contingents along Mambajao’s main roads.",
        descriptionFil: "Makulay na Sinulog street dancing contingents sa mga pangunahing daan ng Mambajao.",
        descriptionBis: "Mabulukon nga Sinulog street dancing contingents sa mga pangunang dalan sa Mambajao.",
        location: "Mambajao Town Plaza",
      },
      {
        dayEn: "Jan 18",
        dayFil: "Ene 18",
        dayBis: "Ene 18",
        timeEn: "3:00 PM",
        timeFil: "3:00 PM",
        timeBis: "3:00 PM",
        titleEn: "Cultural Dance Presentations",
        titleFil: "Mga Cultural Dance Presentation",
        titleBis: "Mga Cultural Dance Presentation",
        descriptionEn: "Local cultural dance showcases following the street dancing program.",
        descriptionFil: "Mga local cultural dance showcase pagkatapos ng street dancing program.",
        descriptionBis: "Mga local cultural dance showcase human sa street dancing program.",
        location: "Mambajao Town Plaza",
      },
      {
        dayEn: "Jan 18",
        dayFil: "Ene 18",
        dayBis: "Ene 18",
        timeEn: "5:00 PM",
        timeFil: "5:00 PM",
        timeBis: "5:00 PM",
        titleEn: "Trade Fair & Community Night",
        titleFil: "Trade Fair at Community Night",
        titleBis: "Trade Fair ug Community Night",
        descriptionEn: "Local trade booths, food stalls, and community night activities.",
        descriptionFil: "Local trade booths, food stalls, at community night activities.",
        descriptionBis: "Local trade booths, food stalls, ug community night activities.",
        location: "Town Plaza Grounds",
      },
    ],
  },

  "Panaad Holy Week Pilgrimage": {
    overviewEn:
      "Annual penitential pilgrimage along Camiguin’s 64-km circumferential road, with prayers and the Old Volcano Stations of the Cross in Catarman.",
    overviewFil:
      "Taunang penitential pilgrimage sa 64-km circumferential road ng Camiguin, may dasal at Stations of the Cross sa Old Volcano, Catarman.",
    overviewBis:
      "Tuigang penitential pilgrimage sa 64-km circumferential road sa Camiguin, uban ang pag-ampo ug Stations of the Cross sa Old Volcano, Catarman.",
    highlightsEn: [
      "Circumferential road pilgrimage walk",
      "Stations of the Cross at Old Volcano",
      "Holy Week church rites across towns",
      "Traditional starting point: Benoni Port, Mahinog",
    ],
    highlightsFil: [
      "Pilgrimage walk sa circumferential road",
      "Stations of the Cross sa Old Volcano",
      "Mga Holy Week rites sa mga bayan",
      "Tradisyunal na simula: Benoni Port, Mahinog",
    ],
    highlightsBis: [
      "Pilgrimage walk sa circumferential road",
      "Stations of the Cross sa Old Volcano",
      "Mga Holy Week rites sa mga lungsod",
      "Tradisyonal nga pagsugod: Benoni Port, Mahinog",
    ],
    schedule: [
      {
        dayEn: "Apr 1",
        dayFil: "Abr 1",
        dayBis: "Abr 1",
        timeEn: "5:00 AM",
        timeFil: "5:00 AM",
        timeBis: "5:00 AM",
        titleEn: "Pilgrimage Walk Begins · Holy Wednesday",
        titleFil: "Simula ng Pilgrimage Walk · Holy Wednesday",
        titleBis: "Pagsugod sa Pilgrimage Walk · Holy Wednesday",
        descriptionEn: "Devotees may start from any point; Benoni Port is the traditional entry start.",
        descriptionFil: "Maaaring magsimula ang mga deboto saanman; tradisyunal ang Benoni Port bilang entry start.",
        descriptionBis: "Mahimong magsugod ang mga deboto bisan asa; tradisyonal ang Benoni Port isip entry start.",
        location: "Island Loop · Benoni Port",
      },
      {
        dayEn: "Apr 1",
        dayFil: "Abr 1",
        dayBis: "Abr 1",
        timeEn: "All Day",
        timeFil: "Buong Araw",
        timeBis: "Tibuok Adlaw",
        titleEn: "Circumferential Road Trek Continues",
        titleFil: "Patuloy ang Circumferential Road Trek",
        titleBis: "Padayon ang Circumferential Road Trek",
        descriptionEn: "Solo, family, and group pilgrims walk the 64-km island loop at their own pace.",
        descriptionFil: "Solo, pamilya, at group pilgrims na naglalakad sa 64-km island loop sa sariling bilis.",
        descriptionBis: "Solo, pamilya, ug group pilgrims nga naglakaw sa 64-km island loop sa kaugalingong kusog.",
        location: "Camiguin Circumferential Road",
      },
      {
        dayEn: "Apr 2",
        dayFil: "Abr 2",
        dayBis: "Abr 2",
        timeEn: "Morning–Evening",
        timeFil: "Umaga–Gabi",
        timeBis: "Buntag–Gabii",
        titleEn: "Continued Trek & Parish Observances · Maundy Thursday",
        titleFil: "Patuloy na Lakad at Parish Observances · Huwebes Santo",
        titleBis: "Padayong Lakaw ug Parish Observances · Huwebes Santo",
        descriptionEn: "Washing of the Feet and Holy Week rites in parish churches around the island.",
        descriptionFil: "Washing of the Feet at Holy Week rites sa mga parokya sa isla.",
        descriptionBis: "Washing of the Feet ug Holy Week rites sa mga parokya sa isla.",
        location: "Parish churches · Province-wide",
      },
      {
        dayEn: "Apr 2",
        dayFil: "Abr 2",
        dayBis: "Abr 2",
        timeEn: "Evening",
        timeFil: "Gabi",
        timeBis: "Gabii",
        titleEn: "Evening Church Rites",
        titleFil: "Gabi ng Church Rites",
        titleBis: "Gabii sa Church Rites",
        descriptionEn: "Evening Holy Week observances in Camiguin’s parish churches.",
        descriptionFil: "Gabi ng Holy Week observances sa mga parokya ng Camiguin.",
        descriptionBis: "Gabii sa Holy Week observances sa mga parokya sa Camiguin.",
        location: "Parish churches · Province-wide",
      },
      {
        dayEn: "Apr 3",
        dayFil: "Abr 3",
        dayBis: "Abr 3",
        timeEn: "Morning",
        timeFil: "Umaga",
        timeBis: "Buntag",
        titleEn: "Good Friday Processions",
        titleFil: "Prusisyon sa Biyernes Santo",
        titleBis: "Prusisyon sa Biyernes Santo",
        descriptionEn: "Town processions including Mambajao’s historic carozas of the Passion.",
        descriptionFil: "Mga prusisyon sa bayan kasama ang historic carozas ng Passion sa Mambajao.",
        descriptionBis: "Mga prusisyon sa lungsod lakip ang historic carozas sa Passion sa Mambajao.",
        location: "Town centers · Province-wide",
      },
      {
        dayEn: "Apr 3",
        dayFil: "Abr 3",
        dayBis: "Abr 3",
        timeEn: "Daytime",
        timeFil: "Araw",
        timeBis: "Adlaw",
        titleEn: "Old Volcano Stations of the Cross",
        titleFil: "Stations of the Cross sa Old Volcano",
        titleBis: "Stations of the Cross sa Old Volcano",
        descriptionEn: "Ascent to the Walkway to the Old Volcano for the 15 life-size Stations of the Cross.",
        descriptionFil: "Pag-akyat sa Walkway to the Old Volcano para sa 15 life-size Stations of the Cross.",
        descriptionBis: "Pagsaka sa Walkway to the Old Volcano para sa 15 life-size Stations of the Cross.",
        location: "Walkway to the Old Volcano, Catarman",
      },
    ],
  },

  "San Juan Hibok-Hibokan Festival": {
    overviewEn:
      "Province-wide feast of St. John the Baptist with fluvial processions, water sports, and beach gatherings—often at Cabuan and Agohay.",
    overviewFil:
      "Pista ng St. John the Baptist sa buong lalawigan na may fluvial procession, water sports, at beach gatherings—madalas sa Cabuan at Agohay.",
    overviewBis:
      "Pista ni St. John the Baptist sa tibuok lalawigan uban ang fluvial procession, water sports, ug beach gatherings—kasagaran sa Cabuan ug Agohay.",
    highlightsEn: [
      "Fluvial procession",
      "Water sports and boat races",
      "Beach community gatherings",
      "Miss Hibok-Hibokan related activities",
    ],
    highlightsFil: [
      "Fluvial procession",
      "Water sports at boat races",
      "Beach community gatherings",
      "Mga aktibidad kaugnay ng Miss Hibok-Hibokan",
    ],
    highlightsBis: [
      "Fluvial procession",
      "Water sports ug boat races",
      "Beach community gatherings",
      "Mga kalihokan may kalabotan sa Miss Hibok-Hibokan",
    ],
    schedule: [
      {
        dayEn: "Jun 24",
        dayFil: "Hun 24",
        dayBis: "Hun 24",
        timeEn: "7:00 AM",
        timeFil: "7:00 AM",
        timeBis: "7:00 AM",
        titleEn: "Mass & Fluvial Procession",
        titleFil: "Misa at Fluvial Procession",
        titleBis: "Misa ug Fluvial Procession",
        descriptionEn: "Morning mass and fluvial procession honoring St. John the Baptist.",
        descriptionFil: "Umagang misa at fluvial procession bilang pagpaparangal kay St. John the Baptist.",
        descriptionBis: "Buntag nga misa ug fluvial procession isip pagpasidungog kang St. John the Baptist.",
        location: "Coastal barangays · Province-wide",
      },
      {
        dayEn: "Jun 24",
        dayFil: "Hun 24",
        dayBis: "Hun 24",
        timeEn: "10:00 AM",
        timeFil: "10:00 AM",
        timeBis: "10:00 AM",
        titleEn: "Water Sports & Boat Races",
        titleFil: "Water Sports at Boat Races",
        titleBis: "Water Sports ug Boat Races",
        descriptionEn: "Beach games, boat races, and water sports for locals and visitors.",
        descriptionFil: "Beach games, boat races, at water sports para sa lokal at bisita.",
        descriptionBis: "Beach games, boat races, ug water sports para sa lokal ug bisita.",
        location: "Cabuan / Agohay Beaches",
      },
      {
        dayEn: "Jun 24",
        dayFil: "Hun 24",
        dayBis: "Hun 24",
        timeEn: "1:00 PM",
        timeFil: "1:00 PM",
        timeBis: "1:00 PM",
        titleEn: "Beach Community Gathering",
        titleFil: "Beach Community Gathering",
        titleBis: "Beach Community Gathering",
        descriptionEn: "Island-wide beach gatherings continuing through the afternoon.",
        descriptionFil: "Beach gatherings sa buong isla hanggang hapon.",
        descriptionBis: "Beach gatherings sa tibuok isla hangtod hapon.",
        location: "Cabuan / Agohay Beaches",
      },
      {
        dayEn: "Jun 24",
        dayFil: "Hun 24",
        dayBis: "Hun 24",
        timeEn: "4:00 PM",
        timeFil: "4:00 PM",
        timeBis: "4:00 PM",
        titleEn: "Miss Hibok-Hibokan Related Activities",
        titleFil: "Mga Aktibidad kaugnay ng Miss Hibok-Hibokan",
        titleBis: "Mga Kalihokan may kalabotan sa Miss Hibok-Hibokan",
        descriptionEn: "Coronation-related and festive beach program highlights.",
        descriptionFil: "Mga highlight ng coronation-related at festive beach program.",
        descriptionBis: "Mga highlight sa coronation-related ug festive beach program.",
        location: "Cabuan / Agohay Beaches",
      },
    ],
  },

  "Camiguin May Festival & Santacruzan": {
    overviewEn:
      "Month-of-May barangay and town fiesta highlights with Santacruzan processions and Rose of May celebrations across Camiguin.",
    overviewFil:
      "Mga highlight ng May fiesta sa barangay at bayan na may Santacruzan at Rose of May celebrations sa buong Camiguin.",
    overviewBis:
      "Mga highlight sa May fiesta sa barangay ug lungsod uban ang Santacruzan ug Rose of May celebrations sa Camiguin.",
    highlightsEn: [
      "Santacruzan processions",
      "Rose of May search highlights",
      "Barangay and municipal fiesta nights",
    ],
    highlightsFil: [
      "Mga Santacruzan procession",
      "Rose of May search highlights",
      "Barangay at municipal fiesta nights",
    ],
    highlightsBis: [
      "Mga Santacruzan procession",
      "Rose of May search highlights",
      "Barangay ug municipal fiesta nights",
    ],
    schedule: [
      {
        dayEn: "May 15",
        dayFil: "Mayo 15",
        dayBis: "Mayo 15",
        timeEn: "4:00 PM",
        timeFil: "4:00 PM",
        timeBis: "4:00 PM",
        titleEn: "Opening Fiesta Night",
        titleFil: "Opening Fiesta Night",
        titleBis: "Opening Fiesta Night",
        location: "Selected municipal plazas",
      },
      {
        dayEn: "May 16",
        dayFil: "Mayo 16",
        dayBis: "Mayo 16",
        timeEn: "5:00 PM",
        timeFil: "5:00 PM",
        timeBis: "5:00 PM",
        titleEn: "Santacruzan Procession",
        titleFil: "Santacruzan Procession",
        titleBis: "Santacruzan Procession",
        location: "Participating barangays & towns",
      },
      {
        dayEn: "May 17",
        dayFil: "Mayo 17",
        dayBis: "Mayo 17",
        timeEn: "Evening",
        timeFil: "Gabi",
        timeBis: "Gabii",
        titleEn: "Rose of May Culmination Program",
        titleFil: "Rose of May Culmination Program",
        titleBis: "Rose of May Culmination Program",
        location: "Municipal Plazas · Province-wide",
      },
    ],
  },

  "Camiguin Agri-Trade and Food Fair": {
    overviewEn:
      "Three-day showcase of Camiguin farm produce, lanzones products, handicrafts, and local food enterprises at the Capitol Grounds.",
    overviewFil:
      "Tatlong araw na palabas ng farm produce, produkto ng lanzones, handicrafts, at local food enterprises sa Capitol Grounds.",
    overviewBis:
      "Tulo ka adlaw nga pasundayag sa farm produce, produkto sa lanzones, handicrafts, ug local food enterprises sa Capitol Grounds.",
    schedule: [
      {
        dayEn: "Oct 3",
        dayFil: "Okt 3",
        dayBis: "Okt 3",
        timeEn: "8:00 AM",
        timeFil: "8:00 AM",
        timeBis: "8:00 AM",
        titleEn: "Fair Opening Ceremony",
        titleFil: "Opening Ceremony ng Fair",
        titleBis: "Opening Ceremony sa Fair",
        descriptionEn: "Official opening of the agri-trade and food fair.",
        descriptionFil: "Opisyal na pagbubukas ng agri-trade and food fair.",
        descriptionBis: "Opisyal nga pag-abli sa agri-trade and food fair.",
        location: "Capitol Grounds, Mambajao",
      },
      {
        dayEn: "Oct 3",
        dayFil: "Okt 3",
        dayBis: "Okt 3",
        timeEn: "9:00 AM",
        timeFil: "9:00 AM",
        timeBis: "9:00 AM",
        titleEn: "Farmer & MSME Booth Opening",
        titleFil: "Pagbubukas ng Farmer at MSME Booths",
        titleBis: "Pag-abli sa Farmer ug MSME Booths",
        descriptionEn: "Local farm produce, lanzones products, and food enterprise stalls open.",
        descriptionFil: "Bukas ang local farm produce, produkto ng lanzones, at food enterprise stalls.",
        descriptionBis: "Abli ang local farm produce, produkto sa lanzones, ug food enterprise stalls.",
        location: "Capitol Grounds, Mambajao",
      },
      {
        dayEn: "Oct 4",
        dayFil: "Okt 4",
        dayBis: "Okt 4",
        timeEn: "9:00 AM",
        timeFil: "9:00 AM",
        timeBis: "9:00 AM",
        titleEn: "Product Demo Sessions",
        titleFil: "Product Demo Sessions",
        titleBis: "Product Demo Sessions",
        descriptionEn: "Live demos of Camiguin agri and food products.",
        descriptionFil: "Live demos ng agri at food products ng Camiguin.",
        descriptionBis: "Live demos sa agri ug food products sa Camiguin.",
        location: "Capitol Grounds, Mambajao",
      },
      {
        dayEn: "Oct 4",
        dayFil: "Okt 4",
        dayBis: "Okt 4",
        timeEn: "1:00 PM",
        timeFil: "1:00 PM",
        timeBis: "1:00 PM",
        titleEn: "Food Tasting & Local Delicacies",
        titleFil: "Food Tasting at Local Delicacies",
        titleBis: "Food Tasting ug Local Delicacies",
        descriptionEn: "Tasting booths featuring Camiguin’s local food specialties.",
        descriptionFil: "Tasting booths na may local food specialties ng Camiguin.",
        descriptionBis: "Tasting booths nga adunay local food specialties sa Camiguin.",
        location: "Capitol Grounds, Mambajao",
      },
      {
        dayEn: "Oct 5",
        dayFil: "Okt 5",
        dayBis: "Okt 5",
        timeEn: "9:00 AM",
        timeFil: "9:00 AM",
        timeBis: "9:00 AM",
        titleEn: "Closing Sale Day",
        titleFil: "Closing Sale Day",
        titleBis: "Closing Sale Day",
        descriptionEn: "Final fair day for shoppers and product takeaways.",
        descriptionFil: "Huling araw ng fair para sa shoppers at product takeaways.",
        descriptionBis: "Katapusang adlaw sa fair para sa shoppers ug product takeaways.",
        location: "Capitol Grounds, Mambajao",
      },
      {
        dayEn: "Oct 5",
        dayFil: "Okt 5",
        dayBis: "Okt 5",
        timeEn: "4:00 PM",
        timeFil: "4:00 PM",
        timeBis: "4:00 PM",
        titleEn: "Recognition & Closing Program",
        titleFil: "Pagkilala at Closing Program",
        titleBis: "Pagkilala ug Closing Program",
        descriptionEn: "Recognition of exhibitors and closing of the three-day fair.",
        descriptionFil: "Pagkilala sa mga exhibitor at pagsasara ng three-day fair.",
        descriptionBis: "Pagkilala sa mga exhibitor ug pagsira sa three-day fair.",
        location: "Capitol Grounds, Mambajao",
      },
    ],
  },

  "Camiguin Christmas Festival of Lights": {
    overviewEn:
      "Holiday lighting, community night market, and Christmas cultural presentations lighting up Mambajao for the season.",
    overviewFil:
      "Holiday lighting, community night market, at Christmas cultural presentations na nagbibigay-liwanag sa Mambajao.",
    overviewBis:
      "Holiday lighting, community night market, ug Christmas cultural presentations nga nagdan-ag sa Mambajao.",
    schedule: [
      {
        dayEn: "Dec 12",
        dayFil: "Dis 12",
        dayBis: "Dis 12",
        timeEn: "5:00 PM",
        timeFil: "5:00 PM",
        timeBis: "5:00 PM",
        titleEn: "Tree Lighting Ceremony",
        titleFil: "Tree Lighting Ceremony",
        titleBis: "Tree Lighting Ceremony",
        descriptionEn: "Official lighting of the Christmas tree and boulevard displays.",
        descriptionFil: "Opisyal na pag-ilaw ng Christmas tree at boulevard displays.",
        descriptionBis: "Opisyal nga pagdan-ag sa Christmas tree ug boulevard displays.",
        location: "Mambajao Boulevard & Town Plaza",
      },
      {
        dayEn: "Dec 12",
        dayFil: "Dis 12",
        dayBis: "Dis 12",
        timeEn: "7:00 PM",
        timeFil: "7:00 PM",
        timeBis: "7:00 PM",
        titleEn: "Opening Night Cultural Program",
        titleFil: "Opening Night Cultural Program",
        titleBis: "Opening Night Cultural Program",
        descriptionEn: "Christmas cultural presentations marking the festival opening.",
        descriptionFil: "Christmas cultural presentations bilang pagbubukas ng festival.",
        descriptionBis: "Christmas cultural presentations isip pag-abli sa festival.",
        location: "Mambajao Town Plaza",
      },
      {
        dayEn: "Dec 13",
        dayFil: "Dis 13",
        dayBis: "Dis 13",
        timeEn: "5:00 PM",
        timeFil: "5:00 PM",
        timeBis: "5:00 PM",
        titleEn: "Community Night Market",
        titleFil: "Community Night Market",
        titleBis: "Community Night Market",
        descriptionEn: "Holiday night market with local food and gift stalls.",
        descriptionFil: "Holiday night market na may local food at gift stalls.",
        descriptionBis: "Holiday night market nga adunay local food ug gift stalls.",
        location: "Mambajao Boulevard",
      },
      {
        dayEn: "Dec 13",
        dayFil: "Dis 13",
        dayBis: "Dis 13",
        timeEn: "7:00 PM",
        timeFil: "7:00 PM",
        timeBis: "7:00 PM",
        titleEn: "Christmas Choir & Cultural Presentations",
        titleFil: "Christmas Choir at Cultural Presentations",
        titleBis: "Christmas Choir ug Cultural Presentations",
        descriptionEn: "Evening choir and cultural performances along the lighted boulevard.",
        descriptionFil: "Gabi ng choir at cultural performances sa lighted boulevard.",
        descriptionBis: "Gabii sa choir ug cultural performances sa lighted boulevard.",
        location: "Mambajao Boulevard",
      },
      {
        dayEn: "Dec 14",
        dayFil: "Dis 14",
        dayBis: "Dis 14",
        timeEn: "5:00 PM",
        timeFil: "5:00 PM",
        timeBis: "5:00 PM",
        titleEn: "Night Market Continues",
        titleFil: "Patuloy ang Night Market",
        titleBis: "Padayon ang Night Market",
        descriptionEn: "Second night of holiday market stalls and visitor activities.",
        descriptionFil: "Pangalawang gabi ng holiday market stalls at visitor activities.",
        descriptionBis: "Ikaduhang gabii sa holiday market stalls ug visitor activities.",
        location: "Mambajao Boulevard",
      },
      {
        dayEn: "Dec 14",
        dayFil: "Dis 14",
        dayBis: "Dis 14",
        timeEn: "7:00 PM",
        timeFil: "7:00 PM",
        timeBis: "7:00 PM",
        titleEn: "Island Lights Cultural Night",
        titleFil: "Island Lights Cultural Night",
        titleBis: "Island Lights Cultural Night",
        descriptionEn: "Community performances under the Christmas festival lights.",
        descriptionFil: "Community performances sa ilalim ng Christmas festival lights.",
        descriptionBis: "Community performances ubos sa Christmas festival lights.",
        location: "Mambajao Town Plaza",
      },
      {
        dayEn: "Dec 15",
        dayFil: "Dis 15",
        dayBis: "Dis 15",
        timeEn: "5:00 PM",
        timeFil: "5:00 PM",
        timeBis: "5:00 PM",
        titleEn: "Final Night Market",
        titleFil: "Huling Night Market",
        titleBis: "Katapusang Night Market",
        descriptionEn: "Last evening of holiday market and boulevard lighting.",
        descriptionFil: "Huling gabi ng holiday market at boulevard lighting.",
        descriptionBis: "Katapusang gabii sa holiday market ug boulevard lighting.",
        location: "Mambajao Boulevard",
      },
      {
        dayEn: "Dec 15",
        dayFil: "Dis 15",
        dayBis: "Dis 15",
        timeEn: "7:30 PM",
        timeFil: "7:30 PM",
        timeBis: "7:30 PM",
        titleEn: "Festival of Lights Culmination",
        titleFil: "Culmination ng Festival of Lights",
        titleBis: "Culmination sa Festival of Lights",
        descriptionEn: "Closing cultural night for Camiguin’s Christmas Festival of Lights.",
        descriptionFil: "Closing cultural night ng Christmas Festival of Lights ng Camiguin.",
        descriptionBis: "Closing cultural night sa Christmas Festival of Lights sa Camiguin.",
        location: "Mambajao Town Plaza",
      },
    ],
  },

  "Dive Camiguin Awareness Weekend": {
    overviewEn:
      "Weekend highlighting Camiguin’s dive sites, reef protection, and responsible diving and snorkel practices.",
    overviewFil:
      "Weekend na nagha-highlight ng dive sites ng Camiguin, proteksyon ng reef, at responsible diving at snorkel practices.",
    overviewBis:
      "Weekend nga nag-highlight sa dive sites sa Camiguin, proteksyon sa reef, ug responsible diving ug snorkel practices.",
    schedule: [
      {
        dayEn: "Nov 28",
        dayFil: "Nob 28",
        dayBis: "Nob 28",
        timeEn: "8:00 AM",
        timeFil: "8:00 AM",
        timeBis: "8:00 AM",
        titleEn: "Dive Briefing & Reef Orientation",
        titleFil: "Dive Briefing at Reef Orientation",
        titleBis: "Dive Briefing ug Reef Orientation",
        descriptionEn: "Safety, reef etiquette, and responsible diving orientation for participants.",
        descriptionFil: "Orientation sa safety, reef etiquette, at responsible diving para sa mga participant.",
        descriptionBis: "Orientation sa safety, reef etiquette, ug responsible diving para sa mga participant.",
        location: "Mambajao Dive Shops",
      },
      {
        dayEn: "Nov 28",
        dayFil: "Nob 28",
        dayBis: "Nob 28",
        timeEn: "10:00 AM",
        timeFil: "10:00 AM",
        timeBis: "10:00 AM",
        titleEn: "Guided Dive / Snorkel Trip · Day 1",
        titleFil: "Guided Dive / Snorkel Trip · Araw 1",
        titleBis: "Guided Dive / Snorkel Trip · Adlaw 1",
        descriptionEn: "Guided awareness trip to selected Camiguin dive and snorkel sites.",
        descriptionFil: "Guided awareness trip sa mga piling dive at snorkel sites ng Camiguin.",
        descriptionBis: "Guided awareness trip sa mga pinili nga dive ug snorkel sites sa Camiguin.",
        location: "Selected Camiguin dive sites",
      },
      {
        dayEn: "Nov 29",
        dayFil: "Nob 29",
        dayBis: "Nob 29",
        timeEn: "8:00 AM",
        timeFil: "8:00 AM",
        timeBis: "8:00 AM",
        titleEn: "Reef Protection Talk",
        titleFil: "Usapan tungkol sa Reef Protection",
        titleBis: "Diskusyon bahin sa Reef Protection",
        descriptionEn: "Short talk on reef protection and visitor guidelines.",
        descriptionFil: "Maikling usapan tungkol sa reef protection at visitor guidelines.",
        descriptionBis: "Mubo nga diskusyon bahin sa reef protection ug visitor guidelines.",
        location: "Mambajao Dive Shops",
      },
      {
        dayEn: "Nov 29",
        dayFil: "Nob 29",
        dayBis: "Nob 29",
        timeEn: "10:00 AM",
        timeFil: "10:00 AM",
        timeBis: "10:00 AM",
        titleEn: "Guided Dive / Snorkel Trip · Day 2",
        titleFil: "Guided Dive / Snorkel Trip · Araw 2",
        titleBis: "Guided Dive / Snorkel Trip · Adlaw 2",
        descriptionEn: "Second-day guided trip reinforcing responsible diving practices.",
        descriptionFil: "Pangalawang araw ng guided trip na may responsible diving practices.",
        descriptionBis: "Ikaduhang adlaw sa guided trip uban ang responsible diving practices.",
        location: "Selected Camiguin dive sites",
      },
    ],
  },
};

export function getEventDetailPack(titleEn: string): EventDetailPack | null {
  return EVENT_DETAILS_BY_TITLE[titleEn] ?? null;
}
